#[cfg(feature = "legacy-egui-ui")]
pub mod brush_settings;
#[cfg(feature = "legacy-egui-ui")]
pub mod command_palette;
#[cfg(feature = "legacy-egui-ui")]
pub mod dock;
#[cfg(feature = "legacy-egui-ui")]
pub mod export_dialog;
#[cfg(feature = "legacy-egui-ui")]
pub mod export_progress;
#[cfg(feature = "legacy-egui-ui")]
pub mod gizmo;
#[cfg(feature = "legacy-egui-ui")]
pub mod help;
#[cfg(feature = "legacy-egui-ui")]
pub mod history_panel;
#[cfg(feature = "legacy-egui-ui")]
pub mod import_dialog;
#[cfg(feature = "legacy-egui-ui")]
pub mod light_gizmo;
#[cfg(feature = "legacy-egui-ui")]
pub mod light_graph;
#[cfg(feature = "legacy-egui-ui")]
pub mod light_linking;
#[cfg(feature = "legacy-egui-ui")]
pub mod lights_panel;
#[cfg(feature = "legacy-egui-ui")]
pub mod node_graph;
#[cfg(feature = "legacy-egui-ui")]
pub mod profiler;
#[cfg(feature = "legacy-egui-ui")]
pub mod properties;
#[cfg(feature = "legacy-egui-ui")]
pub mod quick_toolbar;
#[cfg(feature = "legacy-egui-ui")]
pub mod recovery_dialog;
#[cfg(feature = "legacy-egui-ui")]
pub mod reference_image;
#[cfg(feature = "legacy-egui-ui")]
pub mod render_settings;
#[cfg(feature = "legacy-egui-ui")]
pub mod scene_stats;
#[cfg(feature = "legacy-egui-ui")]
pub mod scene_tree;
#[cfg(feature = "legacy-egui-ui")]
pub mod sculpt_convert_dialog;
#[cfg(feature = "legacy-egui-ui")]
pub mod settings_window;
#[cfg(feature = "legacy-egui-ui")]
pub mod toasts;

pub mod viewport;
