// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String ping() => RustLib.instance.api.crateApiSimplePing();

String bridgeVersion() => RustLib.instance.api.crateApiSimpleBridgeVersion();

String sceneSnapshotJson() =>
    RustLib.instance.api.crateApiSimpleSceneSnapshotJson();

Future<Uint8List> renderPreviewFrame({
  required int width,
  required int height,
  required double timeSeconds,
}) => RustLib.instance.api.crateApiSimpleRenderPreviewFrame(
  width: width,
  height: height,
  timeSeconds: timeSeconds,
);

void orbitCamera({required double deltaX, required double deltaY}) => RustLib
    .instance
    .api
    .crateApiSimpleOrbitCamera(deltaX: deltaX, deltaY: deltaY);

void panCamera({required double deltaX, required double deltaY}) => RustLib
    .instance
    .api
    .crateApiSimplePanCamera(deltaX: deltaX, deltaY: deltaY);

void zoomCamera({required double delta}) =>
    RustLib.instance.api.crateApiSimpleZoomCamera(delta: delta);

String selectNode({BigInt? nodeId}) =>
    RustLib.instance.api.crateApiSimpleSelectNode(nodeId: nodeId);

String selectNodeAtViewport({
  required double mouseX,
  required double mouseY,
  required int width,
  required int height,
  required double timeSeconds,
}) => RustLib.instance.api.crateApiSimpleSelectNodeAtViewport(
  mouseX: mouseX,
  mouseY: mouseY,
  width: width,
  height: height,
  timeSeconds: timeSeconds,
);

String toggleNodeVisibility({required BigInt nodeId}) =>
    RustLib.instance.api.crateApiSimpleToggleNodeVisibility(nodeId: nodeId);

String toggleNodeLock({required BigInt nodeId}) =>
    RustLib.instance.api.crateApiSimpleToggleNodeLock(nodeId: nodeId);

String deleteSelected() => RustLib.instance.api.crateApiSimpleDeleteSelected();

String duplicateSelected() =>
    RustLib.instance.api.crateApiSimpleDuplicateSelected();

String undo() => RustLib.instance.api.crateApiSimpleUndo();

String redo() => RustLib.instance.api.crateApiSimpleRedo();

String focusSelected() => RustLib.instance.api.crateApiSimpleFocusSelected();

String frameAll() => RustLib.instance.api.crateApiSimpleFrameAll();

String cameraFront() => RustLib.instance.api.crateApiSimpleCameraFront();

String cameraTop() => RustLib.instance.api.crateApiSimpleCameraTop();

String cameraRight() => RustLib.instance.api.crateApiSimpleCameraRight();

String cameraBack() => RustLib.instance.api.crateApiSimpleCameraBack();

String cameraLeft() => RustLib.instance.api.crateApiSimpleCameraLeft();

String cameraBottom() => RustLib.instance.api.crateApiSimpleCameraBottom();

String toggleOrthographic() =>
    RustLib.instance.api.crateApiSimpleToggleOrthographic();

String addSphere() => RustLib.instance.api.crateApiSimpleAddSphere();

String addBox() => RustLib.instance.api.crateApiSimpleAddBox();

String addCylinder() => RustLib.instance.api.crateApiSimpleAddCylinder();

String addTorus() => RustLib.instance.api.crateApiSimpleAddTorus();

String resetScene() => RustLib.instance.api.crateApiSimpleResetScene();
