// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_light_id`, `parse_modifier_id`, `parse_operation_id`

String ping() => RustLib.instance.api.crateApiSimplePing();

String bridgeVersion() => RustLib.instance.api.crateApiSimpleBridgeVersion();

String sceneSnapshotJson() =>
    RustLib.instance.api.crateApiSimpleSceneSnapshotJson();

String newScene() => RustLib.instance.api.crateApiSimpleNewScene();

String openScene() => RustLib.instance.api.crateApiSimpleOpenScene();

String openRecentScene({required String path}) =>
    RustLib.instance.api.crateApiSimpleOpenRecentScene(path: path);

String saveScene() => RustLib.instance.api.crateApiSimpleSaveScene();

String saveSceneAs() => RustLib.instance.api.crateApiSimpleSaveSceneAs();

String recoverAutosave() =>
    RustLib.instance.api.crateApiSimpleRecoverAutosave();

String discardRecovery() =>
    RustLib.instance.api.crateApiSimpleDiscardRecovery();

Future<Uint8List> renderPreviewFrame({
  required int width,
  required int height,
  required double timeSeconds,
}) => RustLib.instance.api.crateApiSimpleRenderPreviewFrame(
  width: width,
  height: height,
  timeSeconds: timeSeconds,
);

void orbitCamera({required double deltaX, required double deltaY}) => RustLib
    .instance
    .api
    .crateApiSimpleOrbitCamera(deltaX: deltaX, deltaY: deltaY);

void panCamera({required double deltaX, required double deltaY}) => RustLib
    .instance
    .api
    .crateApiSimplePanCamera(deltaX: deltaX, deltaY: deltaY);

void zoomCamera({required double delta}) =>
    RustLib.instance.api.crateApiSimpleZoomCamera(delta: delta);

String selectNode({BigInt? nodeId}) =>
    RustLib.instance.api.crateApiSimpleSelectNode(nodeId: nodeId);

String selectNodeAtViewport({
  required double mouseX,
  required double mouseY,
  required int width,
  required int height,
  required double timeSeconds,
}) => RustLib.instance.api.crateApiSimpleSelectNodeAtViewport(
  mouseX: mouseX,
  mouseY: mouseY,
  width: width,
  height: height,
  timeSeconds: timeSeconds,
);

String toggleNodeVisibility({required BigInt nodeId}) =>
    RustLib.instance.api.crateApiSimpleToggleNodeVisibility(nodeId: nodeId);

String toggleNodeLock({required BigInt nodeId}) =>
    RustLib.instance.api.crateApiSimpleToggleNodeLock(nodeId: nodeId);

String deleteSelected() => RustLib.instance.api.crateApiSimpleDeleteSelected();

String duplicateSelected() =>
    RustLib.instance.api.crateApiSimpleDuplicateSelected();

String renameNode({required BigInt nodeId, required String name}) =>
    RustLib.instance.api.crateApiSimpleRenameNode(nodeId: nodeId, name: name);

String createOperation({required String operationId}) => RustLib.instance.api
    .crateApiSimpleCreateOperation(operationId: operationId);

String createTransform() =>
    RustLib.instance.api.crateApiSimpleCreateTransform();

String createModifier({required String modifierId}) =>
    RustLib.instance.api.crateApiSimpleCreateModifier(modifierId: modifierId);

String createLight({required String lightId}) =>
    RustLib.instance.api.crateApiSimpleCreateLight(lightId: lightId);

String createSculpt() => RustLib.instance.api.crateApiSimpleCreateSculpt();

String setSelectedPrimitiveParameter({
  required String parameterKey,
  required double value,
}) => RustLib.instance.api.crateApiSimpleSetSelectedPrimitiveParameter(
  parameterKey: parameterKey,
  value: value,
);

String setSelectedMaterialFloat({
  required String fieldId,
  required double value,
}) => RustLib.instance.api.crateApiSimpleSetSelectedMaterialFloat(
  fieldId: fieldId,
  value: value,
);

String setSelectedMaterialColor({
  required String fieldId,
  required double red,
  required double green,
  required double blue,
}) => RustLib.instance.api.crateApiSimpleSetSelectedMaterialColor(
  fieldId: fieldId,
  red: red,
  green: green,
  blue: blue,
);

String setSelectedTransformPosition({
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiSimpleSetSelectedTransformPosition(
  x: x,
  y: y,
  z: z,
);

String setSelectedTransformRotationDegrees({
  required double xDegrees,
  required double yDegrees,
  required double zDegrees,
}) => RustLib.instance.api.crateApiSimpleSetSelectedTransformRotationDegrees(
  xDegrees: xDegrees,
  yDegrees: yDegrees,
  zDegrees: zDegrees,
);

String setSelectedTransformScale({
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiSimpleSetSelectedTransformScale(
  x: x,
  y: y,
  z: z,
);

String setManipulatorMode({required String modeId}) =>
    RustLib.instance.api.crateApiSimpleSetManipulatorMode(modeId: modeId);

String toggleManipulatorSpace() =>
    RustLib.instance.api.crateApiSimpleToggleManipulatorSpace();

String nudgeManipulatorPivotOffset({
  required double x,
  required double y,
  required double z,
}) => RustLib.instance.api.crateApiSimpleNudgeManipulatorPivotOffset(
  x: x,
  y: y,
  z: z,
);

String resetManipulatorPivot() =>
    RustLib.instance.api.crateApiSimpleResetManipulatorPivot();

String nudgeSelectedTranslation({
  required double deltaX,
  required double deltaY,
  required double deltaZ,
}) => RustLib.instance.api.crateApiSimpleNudgeSelectedTranslation(
  deltaX: deltaX,
  deltaY: deltaY,
  deltaZ: deltaZ,
);

String nudgeSelectedRotationDegrees({
  required double deltaXDegrees,
  required double deltaYDegrees,
  required double deltaZDegrees,
}) => RustLib.instance.api.crateApiSimpleNudgeSelectedRotationDegrees(
  deltaXDegrees: deltaXDegrees,
  deltaYDegrees: deltaYDegrees,
  deltaZDegrees: deltaZDegrees,
);

String nudgeSelectedScale({
  required double deltaX,
  required double deltaY,
  required double deltaZ,
}) => RustLib.instance.api.crateApiSimpleNudgeSelectedScale(
  deltaX: deltaX,
  deltaY: deltaY,
  deltaZ: deltaZ,
);

String undo() => RustLib.instance.api.crateApiSimpleUndo();

String redo() => RustLib.instance.api.crateApiSimpleRedo();

String focusSelected() => RustLib.instance.api.crateApiSimpleFocusSelected();

String frameAll() => RustLib.instance.api.crateApiSimpleFrameAll();

String cameraFront() => RustLib.instance.api.crateApiSimpleCameraFront();

String cameraTop() => RustLib.instance.api.crateApiSimpleCameraTop();

String cameraRight() => RustLib.instance.api.crateApiSimpleCameraRight();

String cameraBack() => RustLib.instance.api.crateApiSimpleCameraBack();

String cameraLeft() => RustLib.instance.api.crateApiSimpleCameraLeft();

String cameraBottom() => RustLib.instance.api.crateApiSimpleCameraBottom();

String toggleOrthographic() =>
    RustLib.instance.api.crateApiSimpleToggleOrthographic();

String addSphere() => RustLib.instance.api.crateApiSimpleAddSphere();

String addBox() => RustLib.instance.api.crateApiSimpleAddBox();

String addCylinder() => RustLib.instance.api.crateApiSimpleAddCylinder();

String addTorus() => RustLib.instance.api.crateApiSimpleAddTorus();

String resetScene() => RustLib.instance.api.crateApiSimpleResetScene();
