#![allow(dead_code)]

use crate::keymap::{KeyboardModifiers, SerializableKey};

pub fn modifiers_from_egui(modifiers: &egui::Modifiers) -> KeyboardModifiers {
    KeyboardModifiers {
        ctrl: modifiers.ctrl,
        shift: modifiers.shift,
        alt: modifiers.alt,
    }
}

pub fn modifiers_to_egui(modifiers: KeyboardModifiers) -> egui::Modifiers {
    egui::Modifiers {
        alt: modifiers.alt,
        ctrl: modifiers.ctrl,
        shift: modifiers.shift,
        mac_cmd: false,
        command: modifiers.ctrl,
    }
}

pub fn key_from_egui(key: egui::Key) -> Option<SerializableKey> {
    match key {
        egui::Key::A => Some(SerializableKey::A),
        egui::Key::B => Some(SerializableKey::B),
        egui::Key::C => Some(SerializableKey::C),
        egui::Key::D => Some(SerializableKey::D),
        egui::Key::E => Some(SerializableKey::E),
        egui::Key::F => Some(SerializableKey::F),
        egui::Key::G => Some(SerializableKey::G),
        egui::Key::H => Some(SerializableKey::H),
        egui::Key::I => Some(SerializableKey::I),
        egui::Key::J => Some(SerializableKey::J),
        egui::Key::K => Some(SerializableKey::K),
        egui::Key::L => Some(SerializableKey::L),
        egui::Key::M => Some(SerializableKey::M),
        egui::Key::N => Some(SerializableKey::N),
        egui::Key::O => Some(SerializableKey::O),
        egui::Key::P => Some(SerializableKey::P),
        egui::Key::Q => Some(SerializableKey::Q),
        egui::Key::R => Some(SerializableKey::R),
        egui::Key::S => Some(SerializableKey::S),
        egui::Key::T => Some(SerializableKey::T),
        egui::Key::U => Some(SerializableKey::U),
        egui::Key::V => Some(SerializableKey::V),
        egui::Key::W => Some(SerializableKey::W),
        egui::Key::X => Some(SerializableKey::X),
        egui::Key::Y => Some(SerializableKey::Y),
        egui::Key::Z => Some(SerializableKey::Z),
        egui::Key::Num0 => Some(SerializableKey::Num0),
        egui::Key::Num1 => Some(SerializableKey::Num1),
        egui::Key::Num2 => Some(SerializableKey::Num2),
        egui::Key::Num3 => Some(SerializableKey::Num3),
        egui::Key::Num4 => Some(SerializableKey::Num4),
        egui::Key::Num5 => Some(SerializableKey::Num5),
        egui::Key::Num6 => Some(SerializableKey::Num6),
        egui::Key::Num7 => Some(SerializableKey::Num7),
        egui::Key::Num8 => Some(SerializableKey::Num8),
        egui::Key::Num9 => Some(SerializableKey::Num9),
        egui::Key::F1 => Some(SerializableKey::F1),
        egui::Key::F2 => Some(SerializableKey::F2),
        egui::Key::F3 => Some(SerializableKey::F3),
        egui::Key::F4 => Some(SerializableKey::F4),
        egui::Key::F5 => Some(SerializableKey::F5),
        egui::Key::F6 => Some(SerializableKey::F6),
        egui::Key::F7 => Some(SerializableKey::F7),
        egui::Key::F8 => Some(SerializableKey::F8),
        egui::Key::F9 => Some(SerializableKey::F9),
        egui::Key::F10 => Some(SerializableKey::F10),
        egui::Key::F11 => Some(SerializableKey::F11),
        egui::Key::F12 => Some(SerializableKey::F12),
        egui::Key::Space => Some(SerializableKey::Space),
        egui::Key::Enter => Some(SerializableKey::Enter),
        egui::Key::Escape => Some(SerializableKey::Escape),
        egui::Key::Tab => Some(SerializableKey::Tab),
        egui::Key::Delete => Some(SerializableKey::Delete),
        egui::Key::Home => Some(SerializableKey::Home),
        egui::Key::End => Some(SerializableKey::End),
        egui::Key::ArrowUp => Some(SerializableKey::ArrowUp),
        egui::Key::ArrowDown => Some(SerializableKey::ArrowDown),
        egui::Key::ArrowLeft => Some(SerializableKey::ArrowLeft),
        egui::Key::ArrowRight => Some(SerializableKey::ArrowRight),
        egui::Key::OpenBracket => Some(SerializableKey::OpenBracket),
        egui::Key::CloseBracket => Some(SerializableKey::CloseBracket),
        egui::Key::Slash => Some(SerializableKey::Slash),
        _ => None,
    }
}

pub fn key_to_egui(key: SerializableKey) -> egui::Key {
    match key {
        SerializableKey::A => egui::Key::A,
        SerializableKey::B => egui::Key::B,
        SerializableKey::C => egui::Key::C,
        SerializableKey::D => egui::Key::D,
        SerializableKey::E => egui::Key::E,
        SerializableKey::F => egui::Key::F,
        SerializableKey::G => egui::Key::G,
        SerializableKey::H => egui::Key::H,
        SerializableKey::I => egui::Key::I,
        SerializableKey::J => egui::Key::J,
        SerializableKey::K => egui::Key::K,
        SerializableKey::L => egui::Key::L,
        SerializableKey::M => egui::Key::M,
        SerializableKey::N => egui::Key::N,
        SerializableKey::O => egui::Key::O,
        SerializableKey::P => egui::Key::P,
        SerializableKey::Q => egui::Key::Q,
        SerializableKey::R => egui::Key::R,
        SerializableKey::S => egui::Key::S,
        SerializableKey::T => egui::Key::T,
        SerializableKey::U => egui::Key::U,
        SerializableKey::V => egui::Key::V,
        SerializableKey::W => egui::Key::W,
        SerializableKey::X => egui::Key::X,
        SerializableKey::Y => egui::Key::Y,
        SerializableKey::Z => egui::Key::Z,
        SerializableKey::Num0 => egui::Key::Num0,
        SerializableKey::Num1 => egui::Key::Num1,
        SerializableKey::Num2 => egui::Key::Num2,
        SerializableKey::Num3 => egui::Key::Num3,
        SerializableKey::Num4 => egui::Key::Num4,
        SerializableKey::Num5 => egui::Key::Num5,
        SerializableKey::Num6 => egui::Key::Num6,
        SerializableKey::Num7 => egui::Key::Num7,
        SerializableKey::Num8 => egui::Key::Num8,
        SerializableKey::Num9 => egui::Key::Num9,
        SerializableKey::F1 => egui::Key::F1,
        SerializableKey::F2 => egui::Key::F2,
        SerializableKey::F3 => egui::Key::F3,
        SerializableKey::F4 => egui::Key::F4,
        SerializableKey::F5 => egui::Key::F5,
        SerializableKey::F6 => egui::Key::F6,
        SerializableKey::F7 => egui::Key::F7,
        SerializableKey::F8 => egui::Key::F8,
        SerializableKey::F9 => egui::Key::F9,
        SerializableKey::F10 => egui::Key::F10,
        SerializableKey::F11 => egui::Key::F11,
        SerializableKey::F12 => egui::Key::F12,
        SerializableKey::Space => egui::Key::Space,
        SerializableKey::Enter => egui::Key::Enter,
        SerializableKey::Escape => egui::Key::Escape,
        SerializableKey::Tab => egui::Key::Tab,
        SerializableKey::Delete => egui::Key::Delete,
        SerializableKey::Home => egui::Key::Home,
        SerializableKey::End => egui::Key::End,
        SerializableKey::ArrowUp => egui::Key::ArrowUp,
        SerializableKey::ArrowDown => egui::Key::ArrowDown,
        SerializableKey::ArrowLeft => egui::Key::ArrowLeft,
        SerializableKey::ArrowRight => egui::Key::ArrowRight,
        SerializableKey::OpenBracket => egui::Key::OpenBracket,
        SerializableKey::CloseBracket => egui::Key::CloseBracket,
        SerializableKey::Slash => egui::Key::Slash,
    }
}
