// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Flutter bridge API — thin FFI layer between Dart and the Rust core.
/// All public functions here are exposed to Dart via flutter_rust_bridge codegen.
/// Simple hello function to verify the bridge is working end-to-end.
Future<String> helloFromRust() =>
    RustLib.instance.api.crateBridgeHelloFromRust();

/// Returns the wgpu backend name for the default adapter (useful for diagnostics).
Future<String> gpuBackendName() =>
    RustLib.instance.api.crateBridgeGpuBackendName();
